In [50]:
import numpy as np

In [51]:
mylist=[1,2,3]

In [52]:
arr=np.array(mylist)
arr

array([1, 2, 3])

In [53]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [54]:
matform=np.array(matrix)
matform

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2=np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr3=np.arange(0,11,2)
arr3

array([ 0,  2,  4,  6,  8, 10])

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [58]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones(3)

array([1., 1., 1.])

In [60]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.linspace(0.1,0.9,10)

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

In [62]:
#identity matrix creation
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
#uniform distribution
np.random.rand(5)

array([0.10157804, 0.48289295, 0.8847401 , 0.56133601, 0.7765911 ])

In [64]:
#uniform distribution 2d array
np.random.rand(3,3)

array([[0.56500279, 0.54127415, 0.28720896],
       [0.50924256, 0.90505729, 0.95831157],
       [0.21962762, 0.38540013, 0.07468584]])

In [65]:
#standard normal distribution guassian
np.random.randn(2)

array([-0.14449091,  1.31162161])

In [66]:
#standard normal distribution guassian 2d array
np.random.randn(4,4)


array([[ 0.63385752,  0.40334248, -0.24095538, -0.86620046],
       [-0.1507014 ,  1.37770804,  1.74809931,  2.09838004],
       [ 1.85217981, -1.35639572, -1.17287433,  0.67736789],
       [ 1.41406567,  1.28350263,  0.6261111 ,  0.11323164]])

In [67]:
#random number 
singlenum=np.random.randint(0,100)
setofnum=np.random.randint(0,100,25)
print(singlenum)
print(setofnum)

9
[73 83 14 32  4 33 77 98  4 97 17  5 34 98 51 29 26 67 56 36 24 19 95 74
 51]


In [68]:
#reshape the data one format to another format in dimension
setofnum.reshape(5,5)

array([[73, 83, 14, 32,  4],
       [33, 77, 98,  4, 97],
       [17,  5, 34, 98, 51],
       [29, 26, 67, 56, 36],
       [24, 19, 95, 74, 51]])

In [69]:
#finding maximum and minimum value in array
maximum=setofnum.max()
minimum=setofnum.min()
print(maximum)
print(minimum)

98
4


In [70]:
#finding maximum values index location
setofnum.argmax()

7

In [71]:
#finding minimum value index location 
setofnum.argmin()

4

In [72]:
#getting array shape
setofnum.shape

(25,)

In [73]:
setofnum=setofnum.reshape(5,5)

In [74]:
setofnum

array([[73, 83, 14, 32,  4],
       [33, 77, 98,  4, 97],
       [17,  5, 34, 98, 51],
       [29, 26, 67, 56, 36],
       [24, 19, 95, 74, 51]])

In [75]:
setofnum.shape

(5, 5)

In [76]:
#data type of array elements
setofnum.dtype

dtype('int32')

# Numpy Array Indexing

In [84]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[:5]

array([0, 1, 2, 3, 4])

In [85]:
arr[:5]=99

In [86]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [87]:
arr_copy=arr.copy()

In [88]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [89]:
arr_copy[:]=100

In [90]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [91]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [92]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [93]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [144]:
#getting boolean values in matrix format
arr=np.arange(1,11)
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [145]:
bool_arr=arr>5

In [146]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [148]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])