In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4])

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
arr1.shape

(4,)

In [9]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [7]:
arr2.shape

(5,)

In [14]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)

(2, 5)


In [17]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
print("Array ",arr2)
print("Shape ",arr2.shape)
print(arr2.ndim)
print("Size ",arr2.size)
print("type",arr2.dtype)
print("Itemsize ",arr2.itemsize)


Array  [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape  (2, 5)
2
Size  10
type int64
Itemsize  8


In [37]:
### Numpy vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition
print("Addition ",arr1+arr2)

print("Sub ",arr1-arr2)

print("Mul ",arr1*arr2)

print("DIv ",arr1*arr2)

Addition  [11 22 33 44 55]
Sub  [ -9 -18 -27 -36 -45]
Mul  [ 10  40  90 160 250]
DIv  [ 10  40  90 160 250]


In [34]:
arr1+arr2

array([[11, 22, 33, 44, 55],
       [12, 23, 34, 45, 56]])

In [38]:
arr1=np.array([2,3,4,5,6])

print(np.sqrt(arr1))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [39]:
print(np.exp(arr1))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [41]:
print(np.sin(arr1))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [42]:
print(np.log(arr1))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [44]:
### array slicing and indexing

arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])

In [45]:
arr[0][0]

1

In [50]:
arr[1:,2:]

array([[ 7,  8,  9],
       [11, 12, 13]])

In [58]:
arr[:2,2:4]

array([[3, 4],
       [7, 8]])

In [59]:
### Modify array ele

arr[0,0]=100

In [60]:
arr

array([[100,   2,   3,   4,   5],
       [  5,   6,   7,   8,   9],
       [  9,  10,  11,  12,  13]])

In [67]:
### stats normaliziation
### to have mean of 0 and std deviation of 1
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

normalize_data=(data-mean)/std_dev

In [68]:
mean 

3.0

In [69]:
std_dev

1.4142135623730951

In [70]:
normalize_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [75]:
np.mean(data)


3.0

In [74]:
np.median(data)

3.0

In [76]:
np.std(data)

1.4142135623730951

In [77]:
np.var(data)

2.0

In [80]:
arr=np.arange(1,11,1)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])